### ISSUE TITLE
Accept input as a sparse matrix

### ISSUE THREAD

**Issue by rob-p** [canzarlab/Sphetcher#2]
Hi,

  I was wondering if it would be possible to allow input in a sparse matrix format.  When the input is something like the gene expression vectors for each cell, it is _much_ more convenient to not have to write down the (overwhelming majority) of matrix elements that are 0.  Would it be possible to have Sphetcher take input (optionally) in a sparse matrix format (e.g. matrix market triplet format or some such)?

Thanks!
Rob

**Comment by canzarlab** [comment]
Hi Rob, 

Thank you for this  suggestion. Sphetcher currently implements the sketching algorithm only and assumes that the input matrix is the result of all necessary preprocessing steps (e.g. log-transform, PCA) and thus is not expected to be sparse. We are currently working on a Snakemake workflow that integrates Sphetcher into an analysis pipeline that does include all preprocessing (not in C++ but python and R) and several possible downstream analyses. For that, we will also consider a sparse matrix format. I'll keep you posted. 

Thanks
Stefan

**Comment by rob-p** [comment]
Hi Stefan,

  Thanks for the detailed answer.  I think that makes a lot of sense.  I guess I was a bit confused by this part in the README:

> First you need to provide a matrix where rows are samples (cells) and columns are features (genes, transcripts, principal components PCs).

the suggestion that I could pass the gene features directly is what led me to ask about the sparse matrix.  I guess there are good reasons for _not_ running it in this way on a droplet-based single-cell dataset.  Perhaps it's worth bringing this up in the README or suggesting why you would not want to pass in raw gene expression values as features.  Anyway, congrats on the cool method, and I look forward to the Snakemake workflow!

Best,
Rob
