### ISSUE TITLE
Is there a limit for the size of a dataset?

### ISSUE THREAD

**Issue by tanjahausler** [canzarlab/Sphetcher#3]
Hello there,

I was wondering if there is an upper limit for the number of cells for the input?
For a uni-project, I tried running Sphetcher on a dataset of around 8.2 million cells. However, this error occurred:

```
read file in seconds : 139 sec
# of samples: 8195299, n_dim: 50
run box algorithm in seconds : 17 sec
compute cosine distance matrix in seconds : 1250 sec

> sphetcher: sphetcherTime.C:341: int main(int, char**): Assertion `n_points <= n_boxes' failed.
> Aborted

```

Is there a quick fix or should I simply run Sphetcher on a smaller dataset?
 
Thanks!
Tanja

**Comment by vanhoan310** [comment]
Dear Tanja,

Sorry for our late reply. We set the limit for the sketch size before. We have just increased the limit for the sketch size. Please let me know if you still have any problem.
